### ISSUE TITLE
No content appearing on some pages

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_demo#104]
https://test.localgovdrupal.org/adult-health-and-social-care/support-your-home

![image](https://user-images.githubusercontent.com/3852805/225905144-1ab7a083-50c1-45a4-bf0b-275c8426d9e4.png)

@danchamp - did you tell me you new the reason for this?

**Comment by danchamp** [comment]
@msayoung It's something to with the way child pages are defined in the content yaml for sub-landing pages.

This is the only demo sub-landing page that correctly renders its children: https://demo.localgovdrupal.org/libraries-leisure-and-culture/z-sports-and-activities

The difference seems to be that it explicitly defines URIs for child pages:

https://github.com/localgovdrupal/localgov_demo/blob/6466785f2a280b970686a131463ead7777eae3db/content/node/7c3be0a3-c5b6-4f24-8663-17356d86dd31.yml#L50-L84

All other sub-landing pages appear to omit this.

I tried a quick test of setting the child pages in the UI and exporting the demo content, but it output `target_uuid` instead of `uri` if I used the autocomplete for node references:

```          
          topic_list_links:
            -
              target_uuid: 8d774d57-90ee-44bf-82d0-1f468010bbf0
              title: ''
              options: {  }
            -
              target_uuid: ce3110d2-90f6-45dc-b202-ad8f3df9e5a2
              title: ''
              options: {  }
```

And when re-importing this it didn't work and child pages weren't set.

To get it to output uri I had to drag-and-drop the items from 'Pages linking here'.

So I guess the demo content needs a bit of tidying, re-exporting, and testing.
