### ISSUE TITLE
Broken/missing handler on Directory Channel view

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_demo#94]
On fresh installs, after enabling directories, the contextual filters are broken; it just says Broken/missing handler. This means that once the Demo module is enabled all directory items are listed on all directory channels.

The message from the broken handler is 

```
Configure contextual filter: Broken/missing handler

The handler for this item is broken or missing. The following details are available:

    id: localgov_directory_channels
    table: search_api_index_localgov_directories_index_default
    field: localgov_directory_channels
    relationship: none
    group_type: group
    admin_label:
    plugin_id: search_api
    default_action: not found
    title_enable:
    title:
    default_argument_type: fixed
    default_argument_skip_url:
    specify_validation:
    break_phrase:
    not: 

Enabling the appropriate module may solve this issue. Otherwise, check to see if there is a module update available.
```
